### ISSUE TITLE
App is not considering hemisphere of base climate!

### ISSUE THREAD

**Issue by pat-schmitt** [OGGM/mb_simulator#9]
At the moment all glaciers are assumed to be in the northern hemisphere (starting the hydrological year in October) and so the climate of glaciers in the southern hemisphere is shifted 6 months (instead of starting with the hydrological year in April also starting in October).

**Comment by fmaussion** [comment]
maybe the simplest would be to avoid hydrological years altogether? Its a bit tricky because the hydro year makes a lot of sense in  many regions

**Comment by fmaussion** [comment]
let;s discuss this afternoon
